### ISSUE TITLE
Fedora 28 support

### ISSUE THREAD

**Issue by alunux** [dustymabe/fedora-azure-img-prep#2]
Hi, thank you for providing these very useful scripts. Any update for Fedora 28?

**Comment by dustymabe** [comment]
as far as I know you should be able to use the f28 images we publish directly

**Comment by dustymabe** [comment]
see also: https://gist.github.com/baude/03ddc7198a43fe1a007b10a1fecd268f

**Comment by alunux** [comment]
Amazing! Fedora 28 Cloud works out of the box on Azure. I have networking issue after it's deployed first time. The issue disappeared after I rebooted the VM. Thank you for your help, have a nice weekend.
